---
- include: compat.yml

# Update APT configuration
- name: add universe repository
  apt_repository: >
    repo="deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state=present
  register: universe_result
  sudo: yes

# https://www.teamviewer.com/en/help/363-how-do-i-install-teamviewer-on-my-linux-distribution
- name: Ensure amd64 arch support
  lineinfile: dest=/var/lib/dpkg/arch line="amd64" create=yes
  sudo: yes

# https://www.teamviewer.com/en/help/363-how-do-i-install-teamviewer-on-my-linux-distribution
- name: Ensure i386 arch support
  lineinfile: dest=/var/lib/dpkg/arch line="i386" create=yes
  sudo: yes

# Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  sudo: yes
  when: universe_result.changed

- name: install gdebi
  apt: name=gdebi
  sudo: yes

- name: Check if teamviewer is installed
  command: dpkg-query -W teamviewer
  register: check_teamviewer
  failed_when: false
  changed_when: false

- name: Download Ubuntu teamviewer package
  command: wget -O {{teamviewer_tmp_deb}} {{teamviewer_url_deb}}
  args:
    creates: "{{teamviewer_tmp_deb}}"
  when: check_teamviewer.rc == 1

- name: Install Ubuntu teamviewer package
  sudo: true
  command: gdebi --non-interactive {{teamviewer_tmp_deb}}
  when: check_teamviewer.rc == 1
